version: "3.8"
services:
  test-game:
    image: keihatsu/nodejschatapp:latest
    build: .
    container_name: something_larry
    ports:
      - "80:1000"
    # change port for new builds
    environment:
      - PORT=1000
    volumes:
      - ./:/app
      # verify that file has app.js or index.js
    command: ["node", "index.js"]